Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "web" do |web|
    config.vm.box = "obihann/nginx"
    config.vm.box_version = "0.0.1"
  end

  # config.vm.define "db" do |db|
  #   db.vm.box = "mysql"
  # end
end
