frontend:
  image: saraswat2385/frontend:latest
  ports:
   - "443:443"
  links:
     - backend
  container_name: frontend
backend:
  image: saraswat2385/backend:latest
  ports:
   - "8081:8080"
  container_name: backend
